#false时为单机模式，true时为zookeeper高可用模式
canal.client.instances.example.clusterEnabled: false
canal.client.instances.example.host: 10.2.192.31
#zookeeper 地址
#canal.client.instances.example.zookeeperAddress: 10.2.192.231:2181,10.2.192.232:2181,10.2.192.233:2181

canal.client.instances.example.port: 11111
canal.client.instances.example.batchSize: 1000
canal.client.instances.example.acquireInterval: 1000
canal.client.instances.example.retryCount: 20

spring.main.allow-bean-definition-overriding: true


hive:
  url: jdbc:hive2://10.2.192.233:10000
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  type: com.alibaba.druid.pool.DruidDataSource
  user: hive
  password: hive
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 1
  minIdle: 3
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20

dir:
  deletedDirUpload: /home/hive/increment_data/upload/delete
  deletedDirMerge: /home/hive/increment_data/merge/delete
  updateDirUpload: /home/hive/increment_data/upload/update
  updateDirMerge: /home/hive/increment_data/merge/update
  insertDirUpload: /home/hive/increment_data/upload/insert
  insertDirMerge: /home/hive/increment_data/merge/insert
